// DO NOT EDIT THIS FILE
// This file was generated with SUS Compiler 0.1.1// ::fp_add_test
module fp_add_test(
	input aclk,
	input wire [31:0] A1,
	input wire [31:0] B1,
	output /*mux_wire*/ logic [31:0] Result
);

/*mux_wire*/ logic [31:0] fpa_s_axis_a_tdata;
/*mux_wire*/ logic [31:0] fpa_s_axis_b_tdata;
wire [31:0] fpa_m_axis_result_tdata;
floating_point_0 fpa(
	.aclk(aclk),
	.s_axis_a_tdata(fpa_s_axis_a_tdata),
	.s_axis_b_tdata(fpa_s_axis_b_tdata),
	.m_axis_result_tdata(fpa_m_axis_result_tdata)
);
always_comb begin
	// Combinatorial wires are not defined when not valid. This is just so that the synthesys tool doesn't generate latches
	Result[0] = 'x;
	Result[1] = 'x;
	Result[2] = 'x;
	Result[3] = 'x;
	Result[4] = 'x;
	Result[5] = 'x;
	Result[6] = 'x;
	Result[7] = 'x;
	Result[8] = 'x;
	Result[9] = 'x;
	Result[10] = 'x;
	Result[11] = 'x;
	Result[12] = 'x;
	Result[13] = 'x;
	Result[14] = 'x;
	Result[15] = 'x;
	Result[16] = 'x;
	Result[17] = 'x;
	Result[18] = 'x;
	Result[19] = 'x;
	Result[20] = 'x;
	Result[21] = 'x;
	Result[22] = 'x;
	Result[23] = 'x;
	Result[24] = 'x;
	Result[25] = 'x;
	Result[26] = 'x;
	Result[27] = 'x;
	Result[28] = 'x;
	Result[29] = 'x;
	Result[30] = 'x;
	Result[31] = 'x;
	Result = fpa_m_axis_result_tdata;
end
always_comb begin
	// Combinatorial wires are not defined when not valid. This is just so that the synthesys tool doesn't generate latches
	fpa_s_axis_a_tdata[0] = 'x;
	fpa_s_axis_a_tdata[1] = 'x;
	fpa_s_axis_a_tdata[2] = 'x;
	fpa_s_axis_a_tdata[3] = 'x;
	fpa_s_axis_a_tdata[4] = 'x;
	fpa_s_axis_a_tdata[5] = 'x;
	fpa_s_axis_a_tdata[6] = 'x;
	fpa_s_axis_a_tdata[7] = 'x;
	fpa_s_axis_a_tdata[8] = 'x;
	fpa_s_axis_a_tdata[9] = 'x;
	fpa_s_axis_a_tdata[10] = 'x;
	fpa_s_axis_a_tdata[11] = 'x;
	fpa_s_axis_a_tdata[12] = 'x;
	fpa_s_axis_a_tdata[13] = 'x;
	fpa_s_axis_a_tdata[14] = 'x;
	fpa_s_axis_a_tdata[15] = 'x;
	fpa_s_axis_a_tdata[16] = 'x;
	fpa_s_axis_a_tdata[17] = 'x;
	fpa_s_axis_a_tdata[18] = 'x;
	fpa_s_axis_a_tdata[19] = 'x;
	fpa_s_axis_a_tdata[20] = 'x;
	fpa_s_axis_a_tdata[21] = 'x;
	fpa_s_axis_a_tdata[22] = 'x;
	fpa_s_axis_a_tdata[23] = 'x;
	fpa_s_axis_a_tdata[24] = 'x;
	fpa_s_axis_a_tdata[25] = 'x;
	fpa_s_axis_a_tdata[26] = 'x;
	fpa_s_axis_a_tdata[27] = 'x;
	fpa_s_axis_a_tdata[28] = 'x;
	fpa_s_axis_a_tdata[29] = 'x;
	fpa_s_axis_a_tdata[30] = 'x;
	fpa_s_axis_a_tdata[31] = 'x;
	fpa_s_axis_a_tdata = A1;
end
always_comb begin
	// Combinatorial wires are not defined when not valid. This is just so that the synthesys tool doesn't generate latches
	fpa_s_axis_b_tdata[0] = 'x;
	fpa_s_axis_b_tdata[1] = 'x;
	fpa_s_axis_b_tdata[2] = 'x;
	fpa_s_axis_b_tdata[3] = 'x;
	fpa_s_axis_b_tdata[4] = 'x;
	fpa_s_axis_b_tdata[5] = 'x;
	fpa_s_axis_b_tdata[6] = 'x;
	fpa_s_axis_b_tdata[7] = 'x;
	fpa_s_axis_b_tdata[8] = 'x;
	fpa_s_axis_b_tdata[9] = 'x;
	fpa_s_axis_b_tdata[10] = 'x;
	fpa_s_axis_b_tdata[11] = 'x;
	fpa_s_axis_b_tdata[12] = 'x;
	fpa_s_axis_b_tdata[13] = 'x;
	fpa_s_axis_b_tdata[14] = 'x;
	fpa_s_axis_b_tdata[15] = 'x;
	fpa_s_axis_b_tdata[16] = 'x;
	fpa_s_axis_b_tdata[17] = 'x;
	fpa_s_axis_b_tdata[18] = 'x;
	fpa_s_axis_b_tdata[19] = 'x;
	fpa_s_axis_b_tdata[20] = 'x;
	fpa_s_axis_b_tdata[21] = 'x;
	fpa_s_axis_b_tdata[22] = 'x;
	fpa_s_axis_b_tdata[23] = 'x;
	fpa_s_axis_b_tdata[24] = 'x;
	fpa_s_axis_b_tdata[25] = 'x;
	fpa_s_axis_b_tdata[26] = 'x;
	fpa_s_axis_b_tdata[27] = 'x;
	fpa_s_axis_b_tdata[28] = 'x;
	fpa_s_axis_b_tdata[29] = 'x;
	fpa_s_axis_b_tdata[30] = 'x;
	fpa_s_axis_b_tdata[31] = 'x;
	fpa_s_axis_b_tdata = B1;
end
endmodule

// ::floating_point_0
// Provided externally
// module floating_point_0(
// 	input clk,
// 	input wire [31:0] s_axis_a_tdata,
// 	input wire [31:0] s_axis_b_tdata,
// 	output /*mux_wire*/ logic [31:0] m_axis_result_tdata
// );

