// DO NOT EDIT THIS FILE
// This file was generated with SUS Compiler 0.1.1// ::fp_add
// Provided externally
// module fp_add(
// 	input clk,
// 	input wire [31:0] s_axis_a_tdata,
// 	input wire [31:0] s_axis_b_tdata,
// 	output /*mux_wire*/ logic [31:0] m_axis_result_tdata
// );

